### ISSUE TITLE
Issue of required black version

### ISSUE THREAD

**Issue by kazyam53** [pfnet/pysen#12]
In setup.py, required version of black is,
>  "black>=19.10b0,<=20.8",

But it's written to install black==21.10b0 on README.md.
And it cause error during executing black.

**Comment by sergeant-wizard** [comment]
If you are using pysen by `pip install pysen[lint]` and have experienced the issue reported in https://github.com/psf/black/issues/2964, we'll address the issue by #13 which will be available in the next release.

Otherwise if your issue is specific to `black==21.10b0` please report the problem with some specific error logs.
Please not that the [version specification your are referring to](https://github.com/pfnet/pysen/blob/733670817bb5df5efb5da77b89c1ec39b853a9ee/setup.py#L43-L51) is merely for scenarios where pysen is installed by `pip install pysen[lint]`. By no means does it imply that pysen is incompatible with versions not specified there.
Indeed we think pysen is compatible with`black==21.10b0`, and that is why we describe it as an example in our README.
